# Deploys using CDK
name: Deploy with CDK

on:
  # Runs workflow when called from another workflow (referred to as a "called" workflow)
  workflow_call:
    secrets:
      gh_token:
        required: true
      private_gh_packages_token:
        required: true
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true
    inputs:
      region:
        required: true
        type: string
      cdk_stack:
        required: true
        type: string

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout codebase
      uses: actions/checkout@v2

    - name: Install nodejs
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: https://npm.pkg.github.com
        scope: "@epoxy-ai"
      env:
        NODE_AUTH_TOKEN: ${{ secrets.gh_token }}

    - name: Update .npmrc
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.private_gh_packages_token }}" >> .npmrc

    - name: CDK Deploy
      uses: youyo/aws-cdk-github-actions@v2
      with:
        cdk_subcommand: deploy
        cdk_stack: ${{ inputs.cdk_stack }}
        cdk_args: '--require-approval never'
        actions_comment: false
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        AWS_DEFAULT_REGION: ${{ inputs.region }}
