name: Upload an artifact to an S3 bucket

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
      s3_bucket:
        required: true
    inputs:
      aws_region:
        required: true
        type: string
      aws_role_to_assume:
        required: true
        type: string
      aws_role_duration_seconds:
        required: false
        type: number
        default: 1200
      artifact_name:
        required: true
        type: string

jobs:
  upload_schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Download the artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1.0.3
        with:
          version: 2
      - name: Install configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: ${{ inputs.aws_role_to_assume }}
          role-duration-seconds: ${{ inputs.aws_role_duration_seconds }} 
          aws-region: ${{ inputs.aws_region }}
      - name: Upload API spec file to s3
        run: aws s3 cp ${{ inputs.artifact_name }} s3://${{ secrets.s3_bucket }}/${{ inputs.artifact_name }}
